import type { AppState } from './types'

export const sampleState: AppState = {
  activeGroupId: 'group-weekend',
  groups: [
    {
      id: 'group-weekend',
      name: '週末メンバー',
      emoji: '✊',
      description: 'いつもの4人。勝った者が気持ちよく払う。',
      createdAt: '2026-07-01T10:00:00.000Z',
      members: [
        {
          id: 'member-shigeru',
          name: 'シゲル',
          color: '#D1493F',
          createdAt: '2026-07-01T10:00:00.000Z',
        },
        {
          id: 'member-kenta',
          name: 'ケンタ',
          color: '#1E6A78',
          createdAt: '2026-07-01T10:00:00.000Z',
        },
        {
          id: 'member-yuta',
          name: 'ユウタ',
          color: '#D28C2F',
          createdAt: '2026-07-01T10:00:00.000Z',
        },
        {
          id: 'member-naoki',
          name: 'ナオキ',
          color: '#57508B',
          createdAt: '2026-07-01T10:00:00.000Z',
        },
      ],
    },
  ],
  matches: [
    {
      id: 'match-01',
      groupId: 'group-weekend',
      playedAt: '2026-07-27',
      stake: 'コンビニの新作アイス',
      category: 'snack',
      otokogiId: 'member-yuta',
      participantIds: [
        'member-shigeru',
        'member-kenta',
        'member-yuta',
        'member-naoki',
      ],
      points: 1,
      memo: '炎天下の一本。ごちそうさま！',
      createdAt: '2026-07-27T08:30:00.000Z',
    },
    {
      id: 'match-02',
      groupId: 'group-weekend',
      playedAt: '2026-07-20',
      stake: 'ラーメン全部のせ',
      category: 'meal',
      otokogiId: 'member-shigeru',
      participantIds: [
        'member-shigeru',
        'member-kenta',
        'member-yuta',
        'member-naoki',
      ],
      points: 3,
      memo: '替え玉まで面倒を見てくれた。',
      createdAt: '2026-07-20T12:00:00.000Z',
    },
    {
      id: 'match-03',
      groupId: 'group-weekend',
      playedAt: '2026-07-13',
      stake: 'ドライブのコーヒー',
      category: 'drink',
      otokogiId: 'member-shigeru',
      participantIds: ['member-shigeru', 'member-kenta', 'member-yuta'],
      points: 2,
      memo: '',
      createdAt: '2026-07-13T06:00:00.000Z',
    },
    {
      id: 'match-04',
      groupId: 'group-weekend',
      playedAt: '2026-07-06',
      stake: '映画のポップコーン',
      category: 'snack',
      otokogiId: 'member-kenta',
      participantIds: [
        'member-shigeru',
        'member-kenta',
        'member-yuta',
        'member-naoki',
      ],
      points: 1,
      memo: 'キャラメル味と塩味のハーフ。',
      createdAt: '2026-07-06T09:00:00.000Z',
    },
  ],
}
